### ISSUE TITLE
2018 Staff Team Building Activity

### ISSUE THREAD

**Issue by hessionra** [ICPI/OCM#19]
After the success of last summer's Team Building Scenario, we are looking to do another one this summer.

So far, we are looking into Escape Rooms! @kkale25 said she would look into corporate options and report back.

After we have rates, we can send Doodle with potential dates to ICPI staff. Will also bring up at 4/24 staff meeting.

**Comment by jb3436** [comment]
Let's do an in person off site escape room and see when people are free.

**Comment by hessionra** [comment]
Great! I can do a Doodle poll and circulate.

**Comment by hessionra** [comment]
Sent out invite for June 1st, based on the Doodle poll.
@kkale25 will make a reservation based on the number of RSVPs received by 5/25.
