### ISSUE TITLE
SharePoint Forms

### ISSUE THREAD

**Issue by hessionra** [ICPI/OCM#2]
Process Question: How can we streamline ICPI forms and documents, making them readily accessible on SharePoint?

Projected Audience: ICPI staff, country teams wishing to engage with ICPI, analytic requests

Started with Engagement Form, which is now live on SharePoint: https://www.pepfar.net/OGAC-HQ/icpi/Lists/Engagement/NewForm.aspx

Finalizing Event Request Form. Will work on Cluster Project Proposal next.

**Comment by hessionra** [comment]
Natasha has the updated thematic areas to include in the Engagement Form, and said that it is in the queue for SP team to do.

In the meantime, what are some other forms should we have on SharePoint? Ideas: Project Proposal, CCB request

**Comment by hessionra** [comment]
Now that Engagement Form and Event Form are in SharePoint, are there any other forms we would like to create? Eg. CCB request, Project Proposal, etc. 

@jb3436

**Comment by jb3436** [comment]
@hessionra Yes, I think the CCB request form would be awesome! @abrahamagedewICPI and @kschlenker, what do you think?

Project proposal isn't structured enough to require a form... what else??? Good ideas.

**Comment by hessionra** [comment]
@jb3436 We can brainstorm what would need to be included and how it would be handled!

**Comment by jb3436** [comment]
@hessionra - there is a CCB form (I have attached it here) and saved it[ here on SharePoint.](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FData%20Access%20and%20Quality%20%28DAQ%29%2FDATIM%20CCB%20Process&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) We will need to work on a checklist of what to do when the form comes in. It should go to the DAQ and be a part of the DAQ's project management and make sure it gets transitioend into Zendesk and then the DATIM GitHub repo and then communicated back to the original requestor as it progresses. 
[DATIM_ChangeRequestForm_Template_2018.pdf](https://github.com/ICPI/OCM/files/2274874/DATIM_ChangeRequestForm_Template_2018.pdf)
