### ISSUE TITLE
Transfer ICPI Tracker Tool to GitHub

### ISSUE THREAD

**Issue by hessionra** [ICPI/OCM#29]
During last week's All Staff meeting, we received a suggestion to transfer the ICPI Tracker Tool (which tracks all ICPI tools, their update status, POCs, and SharePoint locations) to GitHub.

Currently the Tracker Tool is based in Excel and can be found on SharePoint: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Tracker%20Tool&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D

Please provide any comments if this is something we should do, or if we should stay with the Excel based version. Thanks!

**Comment by shapaklyak** [comment]
Agree, i think it would be a good idea to explore putting this into GitHub as a project and then you can track "live" each quarter. I can help with this.

**Comment by hessionra** [comment]
We are putting this on the agenda for the next Senior Staff meeting (8/6) to see if it would be more convenient for the cluster leads.

**Comment by hessionra** [comment]
Working with @KatieOC on best layout option for tracker.

**Comment by hessionra** [comment]
Transferred to GitHub and has been used for FY18Q4 initial and clean and FY19Q1 initial. Can be found [here](https://github.com/ICPI/ICPI-Product-Tracker).
