### ISSUE TITLE
Event: Pushing the Limits of Excel: GBV QA Tool

### ISSUE THREAD

**Issue by hessionra** [ICPI/OCM#42]
Event form submitted by @kimisatoPC and @shapaklyak on 3/7 for Brown Bag, "Pushing the Limits of Excel: GBV QA Tool."

Circulated to Leads 3/7.

**Logistic Needs**: Adobe Connect; Recorded Webinar; Conference Line; Conference Room; Wifi 
**Description**: The Prevention Cluster has created an excel-based data entry form and master dashboard to capture data for the gender-based violence quality assurance process that is underway in several PEPFAR countries. Working within the constraints of excel, the Prevention Cluster would like to share lessons learned and best practices of developing an automated data entry form and dashboard. 
**Proposed Event Date**: Monday, April 8th (directly following Inbrief)

**Comment by jb3436** [comment]
@hessionra let's send a save the date out next week

**Comment by kimisatoPC** [comment]
@hessionra @jb3436 @shapaklyak 
Has the save the date been sent out? Also, do we need to submit slides for approval? Many thanks.

**Comment by hessionra** [comment]
Save the date has been sent!
