### ISSUE TITLE
ICPI Vlog Series

### ISSUE THREAD

**Issue by hessionra** [ICPI/OCM#9]
Analytic Question: Best method to communicate to ICPI analysts and staff of current, updated, and new processes and documents?

Audience: ICPI analysts and Staff

Hosted first vlog premiere on 3/22, covered Intro to Slack and ICPI Master Contact List.

**Comment by hessionra** [comment]
Second vlog premiere will be on 4/19, covering Intro to GitHub by @bshook and ICPI Event Form Overview by @kkale25

**Comment by hessionra** [comment]
Next vlogs in pipeline:
ICPI Color Palettes (@shapaklyak )
Visiting ICPI (@kimisatoPC )
Intro to SharePoint/new SharePoint structure (@nmcdavid )
ICPI Engagement Form/Engagement Tracker (@kkale25 )
How to submit CCB request

**Comment by hessionra** [comment]
Time to schedule the third vlog premiere!

@kimisatoPC has recorded a "Visiting ICPI" vlog and @mehtasp & @shazadahmed10 are recording the ICPI Color Palette vlog 4/26.

Next vlogs in pipeline:
ICPI Engagement Tracker (@kkale25 )
Intro SharePoint changes (@aliyahwakil volunteered! Will record next week)
ICPI Inbrief (@HoustonJamie)
How to submit CCB request 
ICPI North America Reservation Calendar

**Comment by hessionra** [comment]
Also possible new vlog idea courtesy of @wvp3 : ICPI PEPFAR Data Calendar and ICPI Tool Calendar.

**Comment by hessionra** [comment]
Exploring OpenEDX platform with ICEE this week (on OCM e-update for 5/17).

Color Palette vlog and Visiting ICPI vlog now linked on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Lists/Links/AllItems.aspx).

Next vlogs to record: Intro to Adobe Connect (Rebecca) and Engagement Log (@kkale25)

**Comment by hessionra** [comment]
Recorded Intro to Adobe Connect vlog today! Will share in OCM E-check in.

@kkale25 are you still recording the Engagement Log piece this week? If so, I will schedule the vlog premiere for next week.

**Comment by kkale25** [comment]
@hessionra Hey! I thought we decided not to do the Vlog premiere next week since all the CDC folks will be out for the Annual Meeting.

**Comment by hessionra** [comment]
@shapaklyak have you been able to explore more into OpenEDX for doing ICPI vlogs?

Also, the next vlogs in pipeline are:
- Adobe Connect Part II: Recording a Meeting (Rebecca)
- New SharePoint Structure/SharePoint overview (volunteers?)

**Comment by shapaklyak** [comment]
@hessionra not yet...but we're exploring next Tuesday.

**Comment by hessionra** [comment]
Adobe Connect Part II: How to record and SharePoint structure vlogs are ready for review! Will be circulated in OCM e-update 8/9.

Tentatively scheduling for 8/21?

**Comment by kkale25** [comment]
We’ll be having office hours for the R training close the normal Vlog time. May not matter but could…?

Could we possibly do the Vlog right after the inbrief on that Monday?

**Comment by hessionra** [comment]
Next steps for vlogs: to move the recordings to PEPFAR Virtual Academy on OpenEdx.

**Comment by jessihandy** [comment]
Closed due to age/redundancy
